//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean turnLeft
        {
            get
            {
                return SteamVR_Actions.default_turnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean turnRight
        {
            get
            {
                return SteamVR_Actions.default_turnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 move
        {
            get
            {
                return SteamVR_Actions.default_move;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.default_pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean triggerAction
        {
            get
            {
                return SteamVR_Actions.default_triggerAction;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
