// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean turnLeft
        {
            get
            {
                return SteamVR_Actions.default_turnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean turnRight
        {
            get
            {
                return SteamVR_Actions.default_turnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 move
        {
            get
            {
                return SteamVR_Actions.default_move;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
